padaria/ext/site/main.py
from flask import Blueprint
from flask import request, render_template, redirect, url_for, session, abort
from flask_login import login_manager
from padaria.ext.site import controllers
from padaria.ext.auth import main as auth
from padaria.ext.db import produtcs as db
from padaria.ext.db import users

bp = Blueprint('site', __name__)


@bp.route('/', methods=['GET','POST'])
def index():
    session.clear()
    if request.method == 'POST':
        login = request.values['username']
        senha = request.values['psw']
        if '@' not in login and login.isnumeric():
            email = controllers.send_email_to_cnpj(login)
            auth = controllers.auth_confirm(email, senha)
            infos = users.info_all(email)
            if auth == 'OKAY' and infos != 'error':
                session['FBLogin'] = infos
                session['filtro'] = 'Todos'
                session['pesquisa'] = ''
                return redirect('/produtos')
            else:
                return render_template('pages/index.html', error='CNPJ / E-mail ou senha incorretos!')
        else:
            auth = controllers.auth_confirm(login, senha)
            infos = controllers.info_user(login)
            if auth == 'OKAY' and infos != 'error':
                session['FBLogin'] = infos
                return redirect('/produtos')
            else:
                return render_template('pages/index.html', error='CNPJ / E-mail ou senha incorretos!')
    return render_template('pages/index.html')


@bp.route('/resetpw', methods=['GET','POST'])
def resetsenha():
    if request.method == 'POST':
        login = request.values['username']
        if '@' not in login and login.isnumeric():
            email = controllers.send_email_to_cnpj(login)
            auth = controllers.send_email_reset_senha(email)
            if auth == 'OKAY':
                return render_template('pages/resetpw_ok.html')
            else:
                return render_template('pages/resetpw.html', error='CNPJ / E-mail não encontrado')
        else:
            auth = controllers.send_email_reset_senha(login)
            if auth == 'OKAY':
                return render_template('pages/resetpw_ok.html')
            else:
                return render_template('pages/resetpw.html', error='CNPJ / E-mail não encontrado')

    return render_template('pages/resetpw.html')


@bp.route('/resetpw/<email>', methods=['GET','POST'])
def resetsenhaconta(email):
    if request.method == 'POST':
        login = request.values['username']
        if '@' not in login and login.isnumeric():
            email = controllers.send_email_to_cnpj(login)
            auth = controllers.send_email_reset_senha(email)
            if auth == 'OKAY':
                return render_template('pages/resetpw_ok.html', email=email)
            else:
                return render_template('pages/resetpw.html', error='CNPJ / E-mail não encontrado', email=email)
        else:
            auth = controllers.send_email_reset_senha(login)
            if auth == 'OKAY':
                return render_template('pages/resetpw_ok.html', email=email)
            else:
                return render_template('pages/resetpw.html', error='CNPJ / E-mail não encontrado', email=email)

    return render_template('pages/resetpw.html', email=email)


@bp.route('/register', methods=['GET', 'POST'])
def register():
    campos = {'cnpj':'', 'nf':'', 'email':'', 'pw':'', 'pw_confirm':'', 'telcel':''}
    if request.method == 'POST':
        dados={}
        for i in campos:
            dados[i] = request.values[i]
        resp = auth.confirm_cadastro(**dados)
        if resp == 'OK':
            return render_template('pages/index.html', ok='Cadastro Realizado com Sucesso')
        elif resp == 'ERROR_S':
            return render_template('pages/registrar.html', error='As Senha Digitadas Não Conferem', dados=dados)
        elif resp == 'ERROR_C':
            return render_template('pages/registrar.html', error='CNPJ Invalido!',dados=dados)
    return render_template('pages/registrar.html',dados=campos)


@bp.route('/produtos', methods=['GET','POST'])
def produtos():
    if 'FBLogin' not in session:
        return abort(401)
    else:
        session['filtro'] = 'Todos'
        session['pesquisa'] = ''
        if request.method == 'POST':
            pesq = request.form['pesquisa']
            f = request.values['filtro']

            session['pesquisa'] = pesq
            session['filtro'] = f

            if pesq != '':
                prod = db.get_all_products(pesquisa=pesq, filtro=f)
            else:
                prod = db.get_all_products(filtro=f)


            if str(session['FBLogin']['admin']) == '1':
                return render_template('pages/produtos.html', empresa=session['FBLogin']['nf'], admin='1', produtos='Meus Produtos',
                                       venda='Propostas', p=prod, f=f, pesq=session['pesquisa'], filt=session['filtro'])
            else:
                return render_template('pages/produtos.html', empresa=session['FBLogin']['nf'], admin='0', produtos='Produtos',
                                       venda='Minha Prospostas', p=prod, f=f, pesq=session['pesquisa'], filt=session['filtro'])
        prod = db.get_all_products()
        if str(session['FBLogin']['admin']) == '1':
            return render_template('pages/produtos.html', empresa=session['FBLogin']['nf'], admin='1', produtos='Meus Produtos', venda='Propostas',p=prod, pesq=session['pesquisa'], filt=session['filtro'])
        else:
            return render_template('pages/produtos.html', empresa=session['FBLogin']['nf'], admin='0', produtos='Produtos', venda='Minha Prospostas',p=prod, pesq=session['pesquisa'], filt=session['filtro'])


@bp.route('/produto/editar/<int:id>', methods=['GET','POST'])
def editar(id):
    if 'FBLogin' not in session:
        return abort(401)
    else:
        if request.method == 'POST':
            form = ['title', 'pricemin', 'pricemax', 'quant', 'uniquant', 'cat', 'prefmark', 'localentrega', 'desc', 'foto']
            infos={'id':id}
            for i in form:
                if i == 'foto':
                    foto = request.files[i]
                    if foto.filename == "":
                        infos[i] = ""
                    else:
                        infos[i]=foto
                else:
                    infos[i] = request.form[i]
            db.update_product(**infos)
            return redirect('/produtos')

        prod = db.get_all_products()
        emp = session['FBLogin']
        if str(emp['admin']) == '1':
            return render_template('pages/produtos.html', empresa=emp['nf'], produtos='Meus Produtos', admin='1',
                                       venda='Propostas', p=prod, produto=prod[str(id)], mod='editar')
        else:
            return render_template('pages/produtos.html', empresa=emp['nf'], produtos='Produtos', admin='0',
                                       venda='Minha Propostas', p=prod, produto=prod[str(id)], mod='editar')

@bp.route('/produto/adicionar', methods=['GET','POST'])
def adicionar():
    if 'FBLogin' not in session:
        return abort(401)
    else:
        if request.method == 'POST':
            nome = request.form['nome']
            quant = request.form['quant']
            selectunit = request.form['selectunit']
            vmin = request.form['vmin']
            vmax = request.form['vmax']
            selectcat = request.form['selectcat']
            pmark = request.form['pmark']
            lentreg = request.form['lentreg']
            desc = request.form['desc']
            foto = request.files['foto']

            db.insert_product(nome,vmin,vmax,quant,selectunit,selectcat,pmark,lentreg,desc,foto)
            return redirect('/produtos')

        prod = db.get_all_products()
        emp = session['FBLogin']
        if str(emp['admin']) == '1':
            return render_template('pages/produtos.html', empresa=emp['nf'], admin='1' ,produtos='Meus Produtos', venda='Propostas',p=prod,mod='adicionar')
        else:
            return render_template('pages/produtos.html', empresa=emp['nf'],admin='0', produtos='Produtos', venda='Minha Prospostas',p=prod,mod='adicionar')


@bp.route('/produto/<int:id>', methods=['GET','POST'])
def modal(id):
    if 'FBLogin' not in session:
        return abort(401)
    else:

        prod = db.get_all_products()
        emp = session['FBLogin']

        if request.method == 'POST':
            vp = request.form['valorproposta']
            qp = request.form['quantproposta']
            unp = request.form.get('selectunit')
            controllers.insert_proposta(cnpj=emp['cnpj'], rs=emp['rs'], end=emp['end'], num=emp['num'], bairro=emp['bairro'],
                                        estado=emp['estado'], cep=emp['cep'], telfixo=emp['telfixo'], telcel=emp['telcel'],
                                        email=emp['email'], vp=vp, qp=f'{qp} {unp}')

            if str(emp['admin']) == '1':
                return render_template('pages/produtos.html', empresa=emp['nf'], produtos='Meus Produtos', admin='1',
                                       venda='Propostas', p=prod, produto=prod[str(id)], mod='2', msg='Proposta Enviada')
            else:
                return render_template('pages/produtos.html', empresa=emp['nf'], produtos='Meus Produtos',
                                       venda='Propostas',
                                       p=prod, produto=prod[str(id)], mod='2', msg='Proposta Enviada', admin='0')

        if str(emp['admin']) == '1':
            return render_template('pages/produtos.html', empresa=emp['nf'],admin='1',produtos='Meus Produtos',
                                   venda='Propostas',p=prod,produto=prod[str(id)],mod='1')
        else:
            return render_template('pages/produtos.html', empresa=emp['nf'],admin='0', produtos='Produtos', p=prod,produto=prod[str(id)],
                                   venda='Minha Prospostas',mod='1')

padaria/templates/pages/account.html
{% extends "base.html" %}

{% block head %}  <title>Minha Conta</title> {% endblock head %}

{% block body %}
<h3 class="title has-text-centered">Minha Conta</h3>
<div class="columns hero is-link is-centered is-multiline">
    <div class="column is-8 is-offset-2 mt-5 mb-5">
        <form action="/minhaconta/editar/{{ dados['id'] }}" class="box" method="POST" enctype="multipart/form-data">
            <div class="field">
                <div class="columns ">
                    <div class="column">
                        <label class="label mb-0">
                            <span class="is-size-7">CNPJ</span>
                        </label>
                        <div class="controll has-icons-left">
                            <input type="number" class="input" name="cnpj" placeholder="{{ dados['cnpj'] }}" id="myInput" value="{{ dados['cnpj'] }}">
                            <span class="icon is-small is-left">
                                <i class="fa fa-envelope"></i>
                            </span>
                        </div>
                        <div class="columns">
                            <div class="column">
                                <label class="label mb-0">
                                    <span class="is-size-7">Endereço</span>
                                </label>
                                <div class="controll has-icons-left">
                                    <input type="text" class="input" name="end" placeholder="{{ dados['end'] }}" id="myInput" value="{{ dados['end'] }}">
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-envelope"></i>
                                    </span>
                                </div>
                            </div>
                            <div class="column is-3">
                                <label class="label mb-0">
                                    <span class="is-size-7">Número</span>
                                </label>
                                <div class="controll has-icons-left">
                                    <input type="text" class="input" name="num" placeholder="{{ dados['num'] }}" id="myInput" value="{{ dados['num'] }}">
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-envelope"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                        

                        <label class="label mb-0">
                            <span class="is-size-7">CEP</span>
                        </label>
                        <div class="controll has-icons-left">
                            <input type="text" class="input" name="cep" placeholder="{{ dados['cep'] }}" value="{{ dados['cep'] }}">
                            <span class="icon is-small is-left">
                                <i class="fa fa-envelope"></i>
                            </span>
                        </div>

                        <label class="label mb-0">
                            <span class="is-size-7">E-mail</span>
                        </label>
                        <div class="controll has-icons-left">
                            <input type="text" class="input" name="email" placeholder="{{ dados['email'] }}" value="{{ dados['email'] }}">
                            <span class="icon is-small is-left">
                                <i class="fa fa-envelope"></i>
                            </span>
                        </div>

                    </div>

                    <div class="column ">
                        <label class="label mb-0">
                            <span class="is-size-7">Razão Social</span>
                        </label>
                        <div class="controll has-icons-left">
                            <input type="text" class="input" name="rs" placeholder="{{ dados['rs'] }}" value="{{ dados['rs'] }}">
                            <span class="icon is-small is-left">
                                <i class="fa fa-envelope"></i>
                            </span>
                        </div>


                        
                        <div class="columns">
                            <div class="column">
                                <label class="label mb-0">
                                    <span class="is-size-7">Bairro</span>
                                </label>
                                <div class="controll has-icons-left">
                                    <input type="text" class="input" name="bairro" placeholder="{{ dados['bairro'] }}" value="{{ dados['bairro'] }}">
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-envelope"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <label class="label mb-0">
                            <span class="is-size-7">Telefone Fixo</span>
                        </label>
                        <div class="controll has-icons-left">
                            <input type="text" class="input" name="telfixo" placeholder="{{ dados['telfixo'] }}" id="myInput" value="{{ dados['telfixo'] }}">
                            <span class="icon is-small is-left">
                                <i class="fa fa-envelope"></i>
                            </span>
                        </div>
                            
                        <div class="has-text-centered is-rounded">
                            <img src="{{ dados['urlimage'] }}" alt="Image">
                        </div>

                        <div id="file-js-example" class="file is-right is-info">
                            <label class="file-label">
                                <input class="file-input" type="file" name="foto">
                                <span class="file-cta">
                                <span class="file-icon">
                                    <i class="fas fa-upload"></i>
                                </span>
                                <span class="file-label">
                                    Foto de Perfil
                                </span>
                                </span>
                                <span class="file-name">
                                Nenhuma foto seleciona...
                                </span>
                            </label>
                        </div>

                          <script>
                            const fileInput = document.querySelector('#file-js-example input[type=file]');
                            fileInput.onchange = () => {
                              if (fileInput.files.length > 0) {
                                const fileName = document.querySelector('#file-js-example .file-name');
                                fileName.textContent = fileInput.files[0].name;
                              }
                            }
                          </script>

                    </div>

                    <div class="column">

                        <label class="label mb-0">
                            <span class="is-size-7">Nome Fantasia</span>
                        </label>
                        <div class="controll has-icons-left">
                            <input type="text" class="input" name="nf" placeholder="{{ dados['nf'] }}" value="{{ dados['nf'] }}">
                            <span class="icon is-small is-left">
                                <i class="fa fa-envelope"></i>
                            </span>
                        </div>

                        <div class="columns">
                            <div class="column">
                                <label class="label mb-0">
                                    <span class="is-size-7">Cidade</span>
                                </label>
                                <div class="controll has-icons-left">
                                    <input type="text" class="input" name="estado" placeholder="{{ dados['estado'] }}" id="myInput" value="{{ dados['estado'] }}">
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-envelope"></i>
                                    </span>
                                </div>
                            </div>
                            <div class="column is-3">
                                <label class="label mb-0">
                                    <span class="is-size-7">UF</span>
                                </label>
                                <div class="controll has-icons-left">
                                    <input type="text" class="input" name="uf" placeholder="{{ dados['uf'] }}" id="myInput" value="{{ dados['uf'] }}">
                                    <span class="icon is-small is-left">
                                        <i class="fa fa-envelope"></i>
                                    </span>
                                </div>
                            </div>
                        </div>

                        <label class="label mb-0">
                            <span class="is-size-7">Telefone Celular</span>
                        </label>
                        <div class="controll has-icons-left">
                            <input type="number" class="input" name="telcel" placeholder="{{ dados['telcel'] }}" id="myInput" value="{{ dados['telcel'] }}">
                            <span class="icon is-small is-left">
                                <i class="fa fa-envelope"></i>
                            </span>
                        </div>

                        <label class="label pt-5">
                            <a class="button is-danger" href="/resetpw/{{ session['FBLogin']['email'] }}"> Refazer Minha Senha </a>
                        </label>


                    </div>
                    
                </div>
            </div>
            <div class="columns has-text-centered">
                <div class="column">
                    <input type="submit" class="button is-link level-left" value="Salvar"></input>
                </div>
            </div>
           </form>
    </div>
</div>
</section>
{% endblock %}

padaria/templates/pages/index.html
{% extends "baseforms.html" %}

{% block head %}  <title>Login</title> {% endblock head %}


{% block form %}
<form action="/" method="post" class="box">
     <div class="label has-text-centered pb-5 pt-5">
         Padaria
     </div>
     <div class="field">
         <label class="label mb-0">
             <span class="is-size-7">E-mail ou CNPJ</span>
         </label>
         <div class="controll has-icons-left">
             <input type="text" class="input" name="username" placeholder="Exemplo@exemplo.com" required>
             <span class="icon is-small is-left">
                 <i class="fa fa-envelope"></i>
             </span>
         </div>
     </div>
     <div class="field">
         <label class="label mb-0">
             <span class="is-size-7">Senha</span>
         </label>
         <div class="controll has-icons-left">
             <input type="password" class="input" name="psw" placeholder="******" required>
             <span class="icon is-small is-left">
                 <i class="fa fa-envelope"></i>
             </span>
         </div>
         <div class="columns">
             <div class="column">
                 <div class="field">
                     <label class="label">
                         <input type="checkbox" class="checkbox">
                         <span class="is-size-7"> Lembrar de mim! </span>
                     </label>
                 </div>
             </div>
             <div class="column">
                 <div class="field">
                     <label class="label">
                        <a class="level-right is-size-7"  href="/resetpw"> Esqueci a senha</a>
                     </label>
                 </div>
             </div>
         </div>
     </div>
     <div class="field has-text-centered pt-1">
         <div class="columns">
             <div class="column">
                 <input type="submit" class="button is-link" value="Entrar"></input>
             </div>
             <div class="column">
                <label class="label">
                    <a class="button" href="{{ url_for('site.register')}}"> Registrar </a>
                </label>
             </div>
         </div>
     </div>
</form>
{% endblock form %}


    {% block error %}
    {% if error %}
    <article class="message is-danger">
        <div class="message-body">
          {{ error }}
        </div>
      </article>
      {% endif %}
      {% if ok %}
      <article class="message is-primary">
          <div class="message-body">
            {{ ok }}
          </div>
        </article>
        {% endif %}
    {% endblock error %}

padaria/templates/pages/registrar.html
{% extends "baseforms.html" %}

{% block head %}  <title>Registrar</title> {% endblock head %}

{% block form %}
<form action="/register" class="box" method="POST">
    <div class="label has-text-centered pb-5 pt-5">
        Padaria
    </div>

    <div class="field">
        <label class="label mb-0">
            <span class="is-size-7">CNPJ</span>
        </label>
        <div class="controll has-icons-left">
            <input type="number" class="input" name="cnpj" placeholder="99.999.999\0009-99" id="myInput" value="{{ dados['cnpj'] }}">
            <span class="icon is-small is-left">
                <i class="fa fa-envelope"></i>
            </span>
        </div>

        <label class="label mb-0">
            <span class="is-size-7">Nome Fantasia</span>
        </label>
        <div class="controll has-icons-left">
            <input type="text" class="input" name="nf" placeholder="EMPRESA" value="{{ dados['nf'] }}">
            <span class="icon is-small is-left">
                <i class="fa fa-envelope"></i>
            </span>
        </div>

        <label class="label mb-0">
            <span class="is-size-7">E-mail</span>
        </label>
        <div class="controll has-icons-left">
            <input type="text" class="input" name="email" placeholder="Exemplo@exemplo.com.br" value="{{ dados['email'] }}">
            <span class="icon is-small is-left">
                <i class="fa fa-envelope"></i>
            </span>
        </div>

        <label class="label mb-0">
            <span class="is-size-7">Telefone Celular</span>
        </label>
        <div class="controll has-icons-left">
            <input type="number" class="input" name="telcel" placeholder="(11)9 9999-999" value="{{ dados['telcel'] }}">
            <span class="icon is-small is-left">
                <i class="fa fa-envelope"></i>
            </span>
        </div>

        
        <label class="label mb-0">
            <span class="is-size-7">Senha</span>
        </label>
        <div class="controll has-icons-left">
            <input type="password" class="input" name="pw" placeholder="*****">
            <span class="icon is-small is-left">
                <i class="fa fa-envelope"></i>
            </span>
        </div>

        <label class="label mb-0">
            <span class="is-size-7">Confirme sua Senha</span>
        </label>
        <div class="controll has-icons-left">
            <input type="password" class="input" name="pw_confirm" placeholder="*****">
            <span class="icon is-small is-left">
                <i class="fa fa-envelope"></i>
            </span>
        </div>

    </div>

    <div class="columns has-text-centered">
        <div class="column">
            <input type="submit" class="button is-link" value="Registrar"></input>
        </div>
        <div class="column ">
            <label class="label">
                <a class="button" href="{{ url_for('site.index')}}"> Entrar </a>
            </label>
        </div>
    </div>
   </form>
{% endblock form %}

{% block error %} 
{% if error %}
<article class="message is-danger">
    <div class="message-body">
      {{ error }}
    </div>
  </article>
{% endif %}

{% if ok %}
  <article class="message is-primary">
      <div class="message-body">
        {{ ok }}
      </div>
    </article>
{% endif %}

{% endblock error %}

padaria/templates/pages/resetpw.html
{% extends "baseforms.html" %}

{% block head %}  <title>Esqueci a Senha</title> {% endblock head %}


{% block form %}
<form action="/resetpw" method="post" class="box">
     <div class="label has-text-centered pb-5 pt-5">
         Padaria
     </div>
     <div class="field">
         <label class="label mb-0">
             <span class="is-size-7">E-mail ou CNPJ</span>
         </label>
         <div class="controll has-icons-left">
             <input type="text" class="input" name="username" placeholder="Exemplo@exemplo.com" value="{{ email }}" required>
             <span class="icon is-small is-left">
                 <i class="fa fa-envelope"></i>
             </span>
         </div>
     </div>
     
     <div class="field has-text-centered pt-1">
         <div class="columns">
             <div class="column">
                 <input type="submit" class="button is-link" value="Recuperar Senha"></input>
             </div>
             <div class="column">
                <label class="label">
                    <a class="button" href="{{ url_for('site.index')}}"> Entrar </a>
                </label>
             </div>
         </div>
     </div>
</form>
{% endblock form %}

{% block error %}
{% if error %}
<article class="message is-danger">
    <div class="message-body">
      {{ error }}
    </div>
  </article>
  {% endif %}
{% endblock error %}

padaria/templates/pages/resetpw_ok.html
{% extends "baseforms.html" %}

{% block head %}  <title>Esqueci a Senha</title> {% endblock head %}


{% block form %}
<form action="" method="post" class="box">
    <div class="label has-text-centered pb-5 pt-5">
        Padaria
    </div>
    <div class="field has-text-centered">
        <label class="label mb-0">
            <span class="is-size-6 has-text-primary">Recuperação de senha enviada a seu e-mail!</span>
            
        </label>
    </div>  
    <div class="field has-text-centered pt-1">
        <div class="columns">
            <div class="column">
               <label class="label">
                   <a class="button" href="{{ url_for('site.index')}}"> Entrar </a>
               </label>
            </div>
        </div>
    </div>
</form>
{% endblock form %}